const CELL_SNAKE_HEAD = 0
const CELL_SNAKE_BODY = 1
const CELL_FOOD = 2
const CELL_CORPSE = 3
const DIRECTION_UP = 0
const DIRECTION_RIGHT = 1
const DIRECTION_LEFT = 2
const DIRECTION_DOWN = 3
const DIRECTION_DIFF_X = [0, 1, -1, 0]
const DIRECTION_DIFF_Y = [-1, 0, 0, 1]

export {
  CELL_SNAKE_HEAD,
  CELL_SNAKE_BODY,
  CELL_FOOD,
  CELL_CORPSE,
  DIRECTION_UP,
  DIRECTION_DOWN,
  DIRECTION_LEFT,
  DIRECTION_RIGHT,
  DIRECTION_DIFF_X,
  DIRECTION_DIFF_Y,
}
